export const ERROR = {
    USERNAME_SHORT: "USERNAME_SHORT",
    USERNAME_LONG: "USERNAME_LONG",
    PASSWORD_SHORT: "PASSWORD_SHORT",
    USERNAME_EXISTS: "USERNAME_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_AUTH: "INVALID_AUTH",
}